# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alternate-toggler-nvim = {
    pname = "alternate-toggler-nvim";
    version = "819800304d3e8e575fd6aa461a8bcf2217e1cfb6";
    src = fetchFromGitHub {
      owner = "rmagatti";
      repo = "alternate-toggler";
      rev = "819800304d3e8e575fd6aa461a8bcf2217e1cfb6";
      fetchSubmodules = false;
      sha256 = "sha256-+UXbgVRki1CGRDHRNrnXOIvzr+0lCAftzGsGVzVQwL4=";
    };
    date = "2024-06-04";
  };
}
