# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  stat-nvim = {
    pname = "stat-nvim";
    version = "81546a867d0b2ae5d7ec57aeb7bf784395343fb4";
    src = fetchFromGitHub {
      owner = "leath-dub";
      repo = "stat.nvim";
      rev = "81546a867d0b2ae5d7ec57aeb7bf784395343fb4";
      fetchSubmodules = false;
      sha256 = "sha256-m27d3ZwXQHz2ilQ0e+o8K+aBcz9ng/+ig8Ss0XLFpnU=";
    };
    date = "2023-09-07";
  };
}
